Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  ExcludedMethods: ['it', 'describe', 'context', 'let', 'specify']
  Exclude:
    - acts_as_hashable.gemspec

AllCops:
  TargetRubyVersion: 2.5

Style/RescueModifier:
  Enabled: false
